### ISSUE TITLE
Edge (Chromium) inspect missing expand arrows for elements

### ISSUE THREAD

**Issue by ekfuhrmann** [ntwigs/Magoon#10]
It looks like the arrows are no longer displaying correctly when inspecting elements.

I'm currently running Edge Version 80.0.320.4

**What I see**:
![image](https://user-images.githubusercontent.com/8878152/68487779-b73ab900-0211-11ea-9b36-5fea9381fd64.png)

**What is expected**:
![image](https://user-images.githubusercontent.com/8878152/68487924-02ed6280-0212-11ea-9e68-9a77fda9264f.png)

Clicking where the icon should be, the functionality is there so it seems like it's strictly a display issue.

**Comment by ntwigs** [comment]
Shit. Suppose I'll have to do something about that 😅

**Comment by ntwigs** [comment]
Well, this didn't solve itself 😅 Suppose I'll have to do this tonight! Hold your thumbs 👍

**Comment by JanisOzolins** [comment]
I'm facing the same issue in Chrome. Is there a fix to this?

**Comment by ntwigs** [comment]
@JanisOzolins It's probably super easy to solve this issue 😓 I'll give it a shot tomorrow 🚀

**Comment by ntwigs** [comment]
@ekfuhrmann @JanisOzolins It has been fixed! 👍
