### ISSUE TITLE
problems understanding installation instructions for chrome console

### ISSUE THREAD

**Issue by columbian-chris** [ntwigs/magoon#26]
In your instructions in the readme, you say to "go to chrome://flags/#enable-devtools-experiments and click enable," but you don't actually mention which specific experiment should be enabled.  There is an extensive list of experiments there.  It's possible that the page has changed since the last update to the readme.

**Comment by ntwigs** [comment]
@columbian-chris I've updated the entire repo and made major changes to *everything*. Give the install instructions a go at https://github.com/ntwigs/magoon/tree/main/themes/chrome-dev-tools 🙏
