### ISSUE TITLE
Color correction on macOS

### ISSUE THREAD

**Issue by LokeCarlsson** [ntwigs/Magoon#5]
Title bar on Visual studio Code is dark grey and looks off from the rest of the theme in macOS.

Please add following color to give a much smoother and better looking theme!

"titleBar.activeBackground": "#232F39"
"titleBar.inactiveBackground": "#232F39"

**Comment by ntwigs** [comment]
@LokeCarlsson Updating the theme right now! :rocket:

**Comment by ntwigs** [comment]
Updated :rocket:
