### ISSUE TITLE
Not rendering properly

### ISSUE THREAD

**Issue by Enteleform** [ntwigs/Magoon#7]
### @ Menu Help / About Google Chrome:
> **Google Chrome is up to date**
> Version 66.0.3359.117 (Official Build) (64-bit)

&nbsp;  
-----
&nbsp;  
Here's what I'm getting:
![magoon](https://user-images.githubusercontent.com/10906415/39286448-08e92556-48ec-11e8-9e28-0fbbb19fabb6.PNG)

&nbsp;
I also tested [**DevTools Theme: Zero Dark Matrix**](https://chrome.google.com/webstore/detail/devtools-theme-zero-dark/bomhdjeadceaggdgfoefmpeafkjhegbo) to make sure that the themes are working properly, didn't have any issues with it.

**Comment by ntwigs** [comment]
@Enteleform Sorry for taking so long - will try to fix this asap! :rocket:

**Comment by LokeCarlsson** [comment]
@Enteleform Can you try again and see if the problem persists?

**Comment by Enteleform** [comment]
Still have the same issue. Syntax highlighting is applied, but the GUI theme is unaffected.

**Comment by avelineamour** [comment]
Same issue here

**Comment by ntwigs** [comment]
Did not mean to close it, but hey, it should be fixed about .. now! :tada:  
@avelineamour  @Enteleform @LokeCarlsson

**Comment by LokeCarlsson** [comment]
It's been working for me the last couple of months! But nice 👍

**Comment by avelineamour** [comment]
Awesome it works now! :)
