### ISSUE TITLE
How's your chrome so nice?

### ISSUE THREAD

**Issue by selrond** [ntwigs/Magoon#9]
How did you achieve that dark look?

![28038854-944ec6e2-65c0-11e7-88a1-3d26f2dc1bc8.png (1920×1080)](https://user-images.githubusercontent.com/14088342/28038854-944ec6e2-65c0-11e7-88a1-3d26f2dc1bc8.png)

**Comment by ntwigs** [comment]
@selrond In Chrome you can choose to use GTK theme. In this case, that would be the Magoon GTK - which derives from Arc-theme. 
[Arc-theme](https://github.com/horst3180/arc-theme)
[Magoon-GTK](https://github.com/ntwigs/Magoon/tree/master/gtk)

**Comment by selrond** [comment]
@ntwigs ah ok, Mac user here :P
